# Nixpacks Configuration for Nitro App

[phases.setup]
nixPkgs = [
  "...", # Extend auto-detected packages
  # Required for sharp image processing
  "vips",
  # Required for playwright/chromium
  "chromium",
  "fontconfig",
  # Required for native modules compilation (better-sqlite3)
  "python3",
  "gcc",
  "gnumake"
]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm preview" 