# Nixpacks Configuration for Nitro App

[phases.setup]
nixPkgs = ["...", "vips", "fontconfig", "python3", "gcc", "gnumake"]

[phases.install]
onlyIncludeFiles = ["package.json", "pnpm-lock.yaml", "pnpm-workspace.yaml"]
cmds = ["pnpm install --frozen-lockfile --ignore-scripts"]

[phases.build]
cmds = [
  "...",
  "pnpm store prune"
]

[start]
runImage = "node:22-bookworm"
onlyIncludeFiles = [".output"]
cmd = "npx playwright@1.53.1 install chromium-headless-shell --with-deps && node .output/server/index.mjs"
