# Nixpacks Configuration for Nitro App

[phases.setup]
nixPkgs = ["...", "vips", "fontconfig", "python3", "gcc", "gnumake"]

[phases.install]
onlyIncludeFiles = ["package.json", "pnpm-lock.yaml", "pnpm-workspace.yaml"]
cmds = ["pnpm install --frozen-lockfile --ignore-scripts"]

[phases.build]
cmds = [
  "...",
  "pnpm store prune"
]

[start]
runImage = "mcr.microsoft.com/playwright:v1.53.1-noble"
onlyIncludeFiles = [".output"]
cmd = "node .output/server/index.mjs"
