# Nixpacks Configuration for Nitro App

[variables]
PLAYWRIGHT_BROWSERS_PATH = "/app/.cache/ms-playwright"

[phases.setup]
nixPkgs = ["...", "vips", "fontconfig", "python3", "gcc", "gnumake"]

[phases.install]
onlyIncludeFiles = ["package.json", "pnpm-lock.yaml", "pnpm-workspace.yaml"]
cmds = ["pnpm install --frozen-lockfile --ignore-scripts"]

[phases.build]
cmds = [
  "pnpm exec playwright install chromium-headless-shell --with-deps",
  "...",
  "pnpm store prune",
]

[start]
runImage = "node:22-bookworm"
onlyIncludeFiles = [".output", ".cache/ms-playwright"]
cmd = "node .output/server/index.mjs"
