packages:
  # all packages in subdirs of packages/ and playground/
  - "packages/**"
  - "playground/**"
  # exclude packages that are inside test directories
  - "!**/test/**"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - better-sqlite3
  - esbuild
  - prisma
  - sharp
